<?php
// Random PHP code generated by AI Assistant
$name = $_POST['name'];
$age = $_POST['age'];
$email = $_POST['email'];
$password = $_POST['password'];

if (isset($_POST['login'])) {
  $username = $_POST['username'];
  if ($username == 'admin') {
    $message = 'Logged in successfully!';
  } else {
    $message = 'Invalid username or password. Please try again.';
  }
} else {
  $message = 'You must provide a valid username and password to log in.';
}

echo $message;
?>
